/**
 * Account Architecture Types & Security Protocols (OPC-48)
 *
 * Defines shared data structures, runtime validators, and security constraints
 * for tool-specific account credential management across Google Antigravity,
 * OpenAI Codex, and Claude Code.
 *
 * Key Invariants:
 * - Renderer-facing interfaces are strictly metadata-only (AccountMetadata)
 * - Credential payloads are opaque UTF-8 strings never exposed to IPC/UI
 * - IDs are strictly validated UUIDs generated by the store
 * - Tool names belong to a strict allowlist
 * - Metadata names are trimmed 1..100 characters with prototype pollution guards
 * - Thrown errors never leak raw credentials, raw inputs, or Node/JSON exceptions
 */

export const MAX_CREDENTIAL_PAYLOAD_SIZE = 5 * 1024 * 1024 // 5 MiB
export const MAX_MANIFEST_FILE_SIZE = 64 * 1024 // 64 KiB

export const DEFAULT_ACCOUNT_ERROR_MESSAGE = '账号操作失败，请检查凭据文件格式与文件权限。'

/**
 * Typed domain error for trusted static messages that are safe to expose across IPC.
 */
export class AccountError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'AccountError'
    Object.setPrototypeOf(this, AccountError.prototype)
  }
}

/**
 * Returns error messages strictly from trusted AccountError instances.
 * All unexpected, raw Node/JSON, or system errors return a safe generic message.
 */
export function sanitizeErrorMessage(error: unknown): string {
  if (error instanceof AccountError) {
    return error.message
  }
  return DEFAULT_ACCOUNT_ERROR_MESSAGE
}

/**
 * Strips Electron remote method invocation wrapper and nested Error prefixes from user-facing error text.
 * Ensures the renderer only receives and displays clean, structured business messages.
 */
export function cleanAccountErrorMessage(
  error: unknown,
  fallback: string = DEFAULT_ACCOUNT_ERROR_MESSAGE
): string {
  if (!error) return fallback
  let message = ''
  if (typeof error === 'string') {
    message = error.trim()
  } else if (error instanceof Error) {
    message = error.message.trim()
  } else if (typeof (error as any)?.message === 'string') {
    message = (error as any).message.trim()
  } else if (typeof (error as any)?.error === 'string') {
    message = (error as any).error.trim()
  }
  while (/^Error invoking remote method '[^']+':\s*/i.test(message)) {
    message = message.replace(/^Error invoking remote method '[^']+':\s*/i, '').trim()
  }
  while (/^Error:\s*/i.test(message)) {
    message = message.replace(/^Error:\s*/i, '').trim()
  }
  if (
    !message ||
    message === '[object Object]' ||
    message.toLowerCase() === 'expired' ||
    message.toLowerCase() === 'error'
  ) {
    message = fallback
  }
  message = message.replace(/https?:\/\/[^\s]+/gi, '[service]')
  message = message.replace(/localhost(:\d+)?/gi, '[service]')
  if (message.length > 240) {
    message = message.slice(0, 237) + '…'
  }
  return message
}

export const ACCOUNT_TOOLS = ['antigravity', 'codex', 'claude-code'] as const
export type AccountTool = (typeof ACCOUNT_TOOLS)[number]

/**
 * Renderer-safe metadata representing a saved account.
 * Credential payload is strictly excluded from this structure.
 */
export interface AccountMetadata {
  id: string
  tool: AccountTool
  name: string
  email?: string
  accountId?: string
  createdAt: number
  updatedAt: number
  expiresAt?: number
}

/** Provider usage windows. An absent percentage is unknown, never zero. */
export type AccountQuotaPeriod = 'weekly' | 'five-hour'

export type AntigravityModelFamily = 'google' | 'openai' | 'claude'

export interface AccountQuotaWindow {
  id: string
  label: string
  /** Explicit provider window duration; absent means the period is unknown. */
  durationSeconds?: number
  /** Optional semantic period used when a provider exposes multiple windows per model. */
  period?: AccountQuotaPeriod
  /** Original model name for a provider window whose label also includes the period. */
  modelLabel?: string
  remainingPercent?: number
  resetsAt?: number
  /** Model family for shared quota pools (e.g. Antigravity google/openai/claude). */
  family?: AntigravityModelFamily
}

export type AccountQuotaStatus = 'ready' | 'unavailable' | 'expired' | 'forbidden' | 'rate-limited' | 'error'

export interface SupportedAntigravityModel {
  id: string
  label: string
  aliases: readonly string[]
  family?: AntigravityModelFamily
}

export const SUPPORTED_ANTIGRAVITY_MODELS: readonly SupportedAntigravityModel[] = [
  {
    id: 'gemini-3.8-flash-high',
    label: 'Gemini 3.8 Flash High',
    aliases: ['gemini-3.8-flash-tiered', 'gemini-3.8-flash'],
    family: 'google',
  },
  {
    id: 'gemini-3.7-flash-medium',
    label: 'Gemini 3.7 Flash Medium',
    aliases: ['gemini-3.7-flash-tiered', 'gemini-3.7-flash'],
    family: 'google',
  },
  { id: 'gemini-3.6-flash-medium', label: 'Gemini 3.6 Flash Medium', aliases: ['gemini-3.6-flash'], family: 'google' },
  { id: 'gemini-3.1-pro-low', label: 'Gemini 3.1 Pro Low', aliases: ['gemini-3.1-pro'], family: 'google' },
  { id: 'claude-sonnet-4.6-thinking', label: 'Claude Sonnet 4.6 (Thinking)', aliases: ['claude-sonnet-4.6'], family: 'claude' },
  { id: 'claude-opus-4.6-thinking', label: 'Claude Opus 4.6 (Thinking)', aliases: ['claude-opus-4.6'], family: 'claude' },
  { id: 'gpt-oss-120b-medium', label: 'GPT-OSS 120B (Medium)', aliases: ['gpt-oss-120b'], family: 'openai' },
]

export function normalizeAntigravityModelName(value: string): string {
  return value
    .toLowerCase()
    .replace(/[()[\]{}]/g, ' ')
    .replace(/[‐‑–—_\-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

export function matchSupportedAntigravityModel(
  candidate: string | undefined | null
): SupportedAntigravityModel | undefined {
  if (!candidate || typeof candidate !== 'string') return undefined
  const cleaned = candidate.endsWith(':weekly') ? candidate.slice(0, -':weekly'.length) : candidate
  const normalized = normalizeAntigravityModelName(cleaned)
  if (!normalized) return undefined

  return SUPPORTED_ANTIGRAVITY_MODELS.find((model) => {
    const normalizedLabel = normalizeAntigravityModelName(model.label)
    const normalizedId = normalizeAntigravityModelName(model.id)
    const normalizedAliases = model.aliases.map(normalizeAntigravityModelName)
    return (
      normalized === normalizedLabel ||
      normalized === normalizedId ||
      normalizedAliases.includes(normalized)
    )
  })
}

/** Safe per-account quota snapshot; contains no authentication material. */
export interface AccountQuotaSnapshot {
  accountId: string
  tool: AccountTool
  status: AccountQuotaStatus
  windows: AccountQuotaWindow[]
  plan?: string
  planReason?: 'restricted-age' | 'unavailable'
  fetchedAt?: number
  attemptedAt: number
  stale?: boolean
}

export type AccountRefreshStatus = 'refreshing' | 'ready' | 'retrying' | 'reauth-required' | 'unsupported' | 'blocked'

/** Credential renewal state only; no tokens or provider response text. */
export interface AccountRefreshState {
  accountId: string
  status: AccountRefreshStatus
  reason?: 'network' | 'rate-limited' | 'invalid-grant' | 'missing-refresh-token' | 'unknown-client' | 'credential-conflict' | 'native-access' | 'runtime-active' | 'storage' | 'invalid-response'
  attemptedAt?: number
  refreshedAt?: number
  retryAt?: number
}

/**
 * Input payload for creating or importing an account.
 * Account IDs are always generated by the store and never accepted from input.
 */
export interface AccountCredentialInput {
  tool: AccountTool
  name: string
  credential: string
  email?: string
  accountId?: string
  expiresAt?: number
}

/**
 * Tool capability report indicating if tool credential switching/capture is supported.
 */
export interface AccountToolCapability {
  tool: AccountTool
  available: boolean
  reason?: string
  reasonCode?: 'codex-auth-conflict' | 'claude-auth-conflict' | 'antigravity-file-mode-required' | 'antigravity-auth-conflict' | 'antigravity-helper-unavailable'
  details?: string
  detailsCode?: 'codex-file' | 'claude-setup-token' | 'antigravity-ssh-file' | 'antigravity-native-keychain'
}

/**
 * Active runtime state of a specific AI developer tool.
 */
export interface AccountToolState {
  tool: AccountTool
  activeAccountId?: string
  activeIdentity?: string
  canRollback: boolean
  recoveryNeeded: boolean
  error?: string
  warning?: string
  autoSwitchEnabled?: boolean
  autoSwitchStatus?: string
}

/**
 * Complete accounts overview report for renderer presentation.
 */
export interface AccountsOverview {
  accounts: AccountMetadata[]
  quotas?: AccountQuotaSnapshot[]
  refreshes?: AccountRefreshState[]
  tools: AccountToolState[]
  capabilities: AccountToolCapability[]
  legacyProfilesPresent: boolean
}

/**
 * Result of an account action (switch, rollback, recover).
 */
export interface AccountActionResult {
  success: boolean
  error?: string
  recoveryNeeded?: boolean
  /** Operation committed, but a follow-up action (such as reopening the client) needs attention. */
  warning?: string
}

export type AccountDiscoveryStatus =
  | 'imported'
  | 'updated'
  | 'unchanged'
  | 'not-found'
  | 'unavailable'
  | 'expired'
  | 'error'
  | 'dismissed'

export interface AccountDiscoveryResult {
  tool: AccountTool
  status: AccountDiscoveryStatus
  accountId?: string
  message?: string
}

export type AccountOAuthPhase = 'waiting' | 'exchanging' | 'succeeded' | 'cancelled' | 'expired' | 'error'

/** Public login progress; OAuth codes, tokens, state and URLs stay in the main process. */
export interface AccountOAuthSession {
  id: string
  tool: AccountTool
  phase: AccountOAuthPhase
  expiresAt: number
  accountId?: string
  error?: string
}

export interface AccountOAuthAPI {
  startOAuth(tool: AccountTool): Promise<AccountOAuthSession>
  getOAuthSession(id: string): Promise<AccountOAuthSession>
  cancelOAuth(id: string): Promise<void>
  reopenOAuth(id: string): Promise<void>
}

/**
 * IPC and service boundary API for account management.
 */
export interface AccountManagementAPI extends AccountOAuthAPI {
  authorizeAntigravityKeychain?(): Promise<void>
  getOverview(): Promise<AccountsOverview>
  refreshQuota(id: string): Promise<AccountQuotaSnapshot>
  captureAccount(input: { tool: AccountTool; name: string }): Promise<AccountMetadata>
  importAccount(input: { tool: AccountTool; name: string; credential: string }): Promise<AccountMetadata>
  syncCurrentAccounts(): Promise<AccountDiscoveryResult[]>
  switchAccount(id: string): Promise<AccountActionResult>
  rollbackAccount(tool: AccountTool): Promise<AccountActionResult>
  recoverAccount(tool: AccountTool): Promise<AccountActionResult>
  renameAccount(id: string, name: string): Promise<AccountMetadata>
  deleteAccount(id: string): Promise<void>
  setAutoSwitch?(tool: AccountTool, enabled: boolean): Promise<boolean>
  getAutoSwitch?(tool: AccountTool): Promise<boolean>
  onAccountsChanged?(listener: () => void): () => void
}

/**
 * Disk manifest stored in ~/.trace/accounts/<id>/manifest.json.
 * Version 1 uses 'credential.utf8'; version 2 uses 'credential.<UUID>.utf8'.
 */
export interface AccountManifest {
  version: 1 | 2
  id: string
  tool: AccountTool
  name: string
  email?: string
  accountId?: string
  createdAt: number
  updatedAt: number
  expiresAt?: number
  credentialFile: string
  payloadSha256: string
  payloadLength: number
}

/**
 * Internal account record combining metadata and opaque payload.
 * Never returned across IPC boundaries.
 */
export interface StoredAccountRecord {
  metadata: AccountMetadata
  credential: string
}

// =========================================================================
// Validation & Security Helpers
// =========================================================================

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const SHA256_REGEX = /^[0-9a-f]{64}$/i
const RESERVED_PROPERTY_NAMES = new Set(['__proto__', 'constructor', 'prototype'])
const CONTROL_CHARS_REGEX = /[\x00-\x1f\x7f]/

export function isAccountTool(tool: unknown): tool is AccountTool {
  return typeof tool === 'string' && (ACCOUNT_TOOLS as readonly string[]).includes(tool as AccountTool)
}

export function validateAccountTool(tool: unknown): AccountTool {
  if (!isAccountTool(tool)) {
    throw new AccountError('Invalid account tool: tool is not supported.')
  }
  return tool
}

export function validateAccountName(name: unknown): string {
  if (typeof name !== 'string') {
    throw new AccountError('Account name must be a non-empty string.')
  }
  const trimmed = name.trim()
  if (trimmed.length < 1 || trimmed.length > 100) {
    throw new AccountError('Account name length must be between 1 and 100 characters.')
  }
  if (RESERVED_PROPERTY_NAMES.has(trimmed)) {
    throw new AccountError('Account name cannot use reserved property names.')
  }
  if (/[/\\:]/.test(trimmed) || CONTROL_CHARS_REGEX.test(trimmed) || trimmed.includes('..')) {
    throw new AccountError('Account name cannot contain path separators, control characters, or path traversal sequences.')
  }
  return trimmed
}

export function validateAccountId(id: unknown): string {
  if (typeof id !== 'string') {
    throw new AccountError('Invalid account ID: must be a valid UUID string.')
  }
  const trimmed = id.trim()
  if (trimmed !== id || !UUID_REGEX.test(trimmed) || RESERVED_PROPERTY_NAMES.has(trimmed) || trimmed.includes('..')) {
    throw new AccountError('Invalid account ID: must be a valid UUID string.')
  }
  return trimmed
}

const CREDENTIAL_V2_FILE_REGEX = /^credential\.[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.utf8$/i

export function validateAccountManifest(manifest: unknown, expectedId?: string): AccountManifest {
  if (!manifest || typeof manifest !== 'object' || Array.isArray(manifest)) {
    throw new AccountError('Account corrupted: manifest must be an object.')
  }

  const m = manifest as Record<string, unknown>
  if (m.version !== 1 && m.version !== 2) {
    throw new AccountError('Account corrupted: unsupported manifest version.')
  }

  if (typeof m.id !== 'string') {
    throw new AccountError('Account corrupted: manifest missing valid id.')
  }
  const validId = validateAccountId(m.id)
  if (expectedId && validId !== expectedId) {
    throw new AccountError('Account corrupted: manifest ID does not match expected ID.')
  }

  const tool = validateAccountTool(m.tool)
  const name = validateAccountName(m.name)

  if (m.email !== undefined) {
    if (
      typeof m.email !== 'string' ||
      m.email.length === 0 ||
      m.email.length > 255 ||
      CONTROL_CHARS_REGEX.test(m.email) ||
      RESERVED_PROPERTY_NAMES.has(m.email)
    ) {
      throw new AccountError('Account corrupted: manifest has invalid email.')
    }
  }

  if (m.accountId !== undefined) {
    if (
      typeof m.accountId !== 'string' ||
      m.accountId.length === 0 ||
      m.accountId.length > 255 ||
      CONTROL_CHARS_REGEX.test(m.accountId) ||
      RESERVED_PROPERTY_NAMES.has(m.accountId)
    ) {
      throw new AccountError('Account corrupted: manifest has invalid accountId.')
    }
  }

  if (typeof m.createdAt !== 'number' || !Number.isInteger(m.createdAt) || m.createdAt <= 0) {
    throw new AccountError('Account corrupted: manifest has invalid createdAt timestamp.')
  }

  if (typeof m.updatedAt !== 'number' || !Number.isInteger(m.updatedAt) || m.updatedAt <= 0) {
    throw new AccountError('Account corrupted: manifest has invalid updatedAt timestamp.')
  }

  if (m.expiresAt !== undefined) {
    if (typeof m.expiresAt !== 'number' || !Number.isInteger(m.expiresAt) || m.expiresAt <= 0) {
      throw new AccountError('Account corrupted: manifest has invalid expiresAt timestamp.')
    }
  }

  if (m.version === 1) {
    if (m.credentialFile !== 'credential.utf8') {
      throw new AccountError('Account corrupted: manifest credentialFile must be exactly credential.utf8.')
    }
  } else {
    if (
      typeof m.credentialFile !== 'string' ||
      (m.credentialFile !== 'credential.utf8' && !CREDENTIAL_V2_FILE_REGEX.test(m.credentialFile))
    ) {
      throw new AccountError('Account corrupted: manifest credentialFile must be a valid credential file pointer.')
    }
  }

  if (typeof m.payloadSha256 !== 'string' || !SHA256_REGEX.test(m.payloadSha256)) {
    throw new AccountError('Account corrupted: manifest has invalid payloadSha256 hash.')
  }

  if (
    typeof m.payloadLength !== 'number' ||
    !Number.isInteger(m.payloadLength) ||
    m.payloadLength <= 0 ||
    m.payloadLength > MAX_CREDENTIAL_PAYLOAD_SIZE
  ) {
    throw new AccountError('Account corrupted: manifest has invalid payloadLength.')
  }

  return {
    version: m.version as 1 | 2,
    id: validId,
    tool,
    name,
    email: m.email as string | undefined,
    accountId: m.accountId as string | undefined,
    createdAt: m.createdAt,
    updatedAt: m.updatedAt,
    expiresAt: m.expiresAt as number | undefined,
    credentialFile: m.credentialFile as string,
    payloadSha256: (m.payloadSha256 as string).toLowerCase(),
    payloadLength: m.payloadLength as number,
  }
}
